In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv("matches.csv")

In [3]:
# Data cleaning
df['city'] = df['city'].ffill()
df.dropna(subset=['winner'], inplace=True)

# Feature selection: only use info available before/at the start of the match
features = ['city', 'team1', 'team2', 'toss_winner', 'toss_decision']
X = df[features]
y = df['winner']

# Encoding categorical variables
X = pd.get_dummies(X, columns=features)
y = pd.get_dummies(y)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Model Lin
lin_model = LinearRegression()
lin_model.fit(X_train,y_train)
lin_pred = lin_model.predict(X_test)
print(f"the lin model pred is {lin_pred[0]}")

the lin model pred is [ 1.48015082e-02  4.02222849e-01  7.73972257e-03  3.97221111e-03
  7.95802864e-03  1.27882367e-02  5.76900474e-03  5.26573491e-01
 -2.19564466e-03  6.15862475e-03  2.70684820e-02 -7.39468417e-03
  4.21249247e-05 -6.50476000e-03  1.00080549e-03]

In [5]:
a = df.tail(1)

In [6]:
a

,match_id,season_id,balls_per_over,city,date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,result
1198,2026028,2026,6,Ahmedabad,2026-04-20,Indian Premier League,30.0,male,T20,T20,...,"Narendra Modi Stadium, Ahmedabad",Mumbai Indians,Gujarat Titans,Mumbai Indians,field,Mumbai Indians,NaN,6.0,NaN,win

In [7]:
a["toss_winner"] = "Gujarat Titans"

In [8]:
a

,match_id,season_id,balls_per_over,city,date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,result
1198,2026028,2026,6,Ahmedabad,2026-04-20,Indian Premier League,30.0,male,T20,T20,...,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Gujarat Titans,Mumbai Indians,field,Mumbai Indians,NaN,6.0,NaN,win

In [9]:
a["win_by_runs"] = 0

In [10]:
a["win_by_wickets"] = 0

In [11]:
a["player_of_match"] = "Tilak Verma"

In [12]:
a

,match_id,season_id,balls_per_over,city,date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,result
1198,2026028,2026,6,Ahmedabad,2026-04-20,Indian Premier League,30.0,male,T20,T20,...,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Gujarat Titans,Mumbai Indians,field,Mumbai Indians,0,0,Tilak Verma,win

In [13]:
a

,match_id,season_id,balls_per_over,city,date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,result
1198,2026028,2026,6,Ahmedabad,2026-04-20,Indian Premier League,30.0,male,T20,T20,...,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Gujarat Titans,Mumbai Indians,field,Mumbai Indians,0,0,Tilak Verma,win